import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import test from 'node:test'

const pluginUrl = new URL('../desktop-plugins/project-kanban/plugin.js', import.meta.url)
const researchUrl = new URL('../desktop-plugins/research-dashboard/plugin.js', import.meta.url)

test('desktop plugin registers the Kanban route below Research', async () => {
  const source = await readFile(pluginUrl, 'utf8')
  const research = await readFile(researchUrl, 'utf8')
  assert.match(source, /SIDEBAR_NAV_AREA/)
  assert.match(source, /path: '\/project-kanban'/)
  assert.match(source, /label: 'Kanban'/)
  assert.match(source, /order: 101/)
  assert.match(research, /SIDEBAR_NAV_AREA, order: 100/)
})

test('desktop plugin uses the scoped backend and responsive lanes', async () => {
  const source = await readFile(pluginUrl, 'utf8')
  assert.match(source, /ctx\.rest\('\/snapshot'/)
  assert.match(source, /board >= 1180 \? 4 : board >= 720 \? 2 : 1/)
  assert.match(source, /project_category/)
  assert.match(source, /Accepted task project/)
  assert.match(source, /data\.stages\.suggested/)
  assert.match(source, /\/inbox\/capture/)
  assert.match(source, /gateway-local/)
  assert.match(source, /human_managed/)
  assert.match(source, /aria-label/)
  assert.doesNotMatch(source, /#[0-9a-fA-F]{3,8}\b/)
})

test('cards carry colored badges, a priority tag, and open a docked detail panel', async () => {
  const source = await readFile(pluginUrl, 'utf8')
  assert.match(source, /function TaskDetail/)
  assert.match(source, /docked \? 'w-80 shrink-0'/)
  assert.match(source, /Escape/)
  assert.match(source, /function cardLinks/)
  assert.match(source, /links\.obsidian/)
  assert.match(source, /links\.github/)
  assert.match(source, /priorityTags/)
  // Colour comes from theme tokens through color-mix, never a literal hex.
  assert.match(source, /color-mix\(in oklch/)
  assert.match(source, /'--ui-blue'/)
  assert.match(source, /'--ui-red'/)
  assert.match(source, /Needs category/)
  assert.match(source, /task\.category === 'unsorted'/)
  // The detail rows name each tool's role rather than copying its contents.
  assert.match(source, /it does not copy them/)
})

test('desktop plugin is opt-in and does not imply unsupported completion controls', async () => {
  const source = await readFile(pluginUrl, 'utf8')
  assert.match(source, /defaultEnabled: false/)
  assert.doesNotMatch(source, /Mark complete|Complete task/)
})

test('Kanban v2 keeps Board first and adds global Projects plus the office Inbox boundary', async () => {
  const source = await readFile(pluginUrl, 'utf8')
  assert.match(source, /Project Kanban/)
  assert.match(source, /children: 'Board'/)
  assert.match(source, /children: 'Projects'/)
  assert.match(source, /children: 'Office Inbox'/)
  assert.match(source, /function Projects/)
  assert.match(source, /function ProjectDetail/)
  assert.match(source, /Unmatched evidence/)
  assert.match(source, /Last observed on/)
  assert.match(source, /Read-only/)
  assert.match(source, /Office Inbox lives on the office desktop/)
  assert.match(source, /project_id/)
  assert.match(source, /aria-label': 'Canonical project'/)
  assert.match(source, /ctx\.os\.openExternal/)
  assert.match(source, /ctx\.os\.revealPath/)
  assert.match(source, /observation\.observed_at/)
  assert.match(source, /observation\.activity_at/)
  assert.match(source, /const selected = narrow/)
  assert.match(source, /gridTemplateColumns: narrow \? 'minmax\(0, 1fr\)' : 'minmax\(280px, 2fr\) minmax\(360px, 3fr\)'/)
  assert.match(source, /onBack \? jsx\(Button/)
  assert.match(source, /onBack: narrow \? \(\) => setSelectedId\(''\) : null/)
  assert.doesNotMatch(source, /mb-2 lg:hidden/)
  assert.match(source, /event\.key === 'Escape' && narrow/)
  assert.match(source, /function InboxCard\(\{ task, mutate, projects \}\)/)
  assert.match(source, /body: \{ title, project_id: projectId \}/)
  assert.doesNotMatch(source, /Accepted task category/)
  assert.doesNotMatch(source, /children: data\.machine\.name/)
})
