#!/usr/bin/env bash
# Strip __PYVENV_LAUNCHER__ from Hermes' Python entry points.
#
# macOS framework Python (first on this machine's PATH) exports
# __PYVENV_LAUNCHER__ to every descendant process. The Hermes Desktop app
# inherits it, `open` re-propagates it across update relaunches, and any
# Python started with it computes sys.path against the wrong interpreter:
#   "Could not find platform dependent libraries <exec_prefix>"
#   ModuleNotFoundError: No module named 'yaml' / 'hermes_cli'
# That is why every `hermes update` hand-off since 2026-08-25 failed and the
# Desktop showed "Hermes couldn't start".
#
# Idempotent; safe to run on a schedule. venv/bin/hermes is regenerated by
# every `hermes update`, so reapply-desktop-patch.sh calls this on each tick.
set -euo pipefail

hermes_root="${HERMES_HOME:-$HOME/.hermes}"
wrapper="$HOME/.local/bin/hermes"
venv_hermes="$hermes_root/hermes-agent/venv/bin/hermes"

patch_wrapper() {
  [[ -f "$wrapper" ]] || return 0
  grep -q "__PYVENV_LAUNCHER__" "$wrapper" && return 0
  # Insert alongside the existing unset lines the wrapper already has.
  sed -i '' 's/^unset PYTHONHOME$/unset PYTHONHOME\nunset __PYVENV_LAUNCHER__/' "$wrapper"
  grep -q "__PYVENV_LAUNCHER__" "$wrapper" || {
    echo "harden-hermes-python-env: failed to patch $wrapper" >&2
    return 1
  }
  echo "Patched $wrapper (unset __PYVENV_LAUNCHER__)."
}

patch_venv_hermes() {
  [[ -f "$venv_hermes" ]] || return 0
  grep -q "__PYVENV_LAUNCHER__" "$venv_hermes" && return 0
  # The file is an sh/python polyglot: sh runs the '''exec' line, python reads
  # lines 2..N as a docstring. Extra sh lines inside the docstring are safe.
  python3 - "$venv_hermes" <<'EOF'
import sys

path = sys.argv[1]
with open(path) as f:
    lines = f.readlines()

old = """'''exec' "$(dirname -- "$(realpath -- "$0")")"/'python3' "$0" "$@"\n"""
if lines[1] != old:
    sys.exit(f"unexpected preamble in {path}; not patching")

lines[1:2] = [
    "'''true' 2>/dev/null\n",
    "unset __PYVENV_LAUNCHER__ PYTHONHOME\n",
    'exec "$(dirname -- "$(realpath -- "$0")")"/python3 "$0" "$@"\n',
]
with open(path, "w") as f:
    f.writelines(lines)
EOF
  "$venv_hermes" --version >/dev/null 2>&1 || {
    echo "harden-hermes-python-env: $venv_hermes broken after patch" >&2
    return 1
  }
  echo "Patched $venv_hermes (unset __PYVENV_LAUNCHER__)."
}

patch_wrapper
patch_venv_hermes
